### ISSUE TITLE
[Request] Optimize code

### ISSUE THREAD

**Issue by cucholix** [nadrino/SimpleModManager#14]
I wonder if it’s possible optimize the code and make the .ovl smaller, most of the overlays are in the 350ish kb SimpleModManager ovl uses 1mb, it often crashes atmosphere when using during gameplay, not sure if the size is to blame though.

Super useful overlay btw!

**Comment by nadrino** [comment]
The main reason why the .ovl is big is because it inheritates from the exact same classes the SMM applet is using. But yeah, it's maybe possible to reduce the final size.
I checked that SMM overlay does not make Atmosphere crash, and especially if there is any memory leak. 
Tesla overlay however crashes sometimes even without launching SMM module (so the .ovl is not even loaded).

Are you able to reproduce the crash you encounter?

**Comment by cucholix** [comment]
It hasn’t produced crashes since 13.0.0 or so. Either an optimization from Nintendo side or atmosphere.
